spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:mem:kotlinpractice
    username: root
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  h2:
    console:
      enabled: true